"""
=========================================================
AGENT 2 — AUDIENCE DISCOVERY AGENT
=========================================================

Purpose:
    Analyze the Content Profile generated by Agent 1 and
    automatically discover who is likely to be interested
    in this content.

Input:
    Content Profile (Structured dictionary from Agent 1)

Output:
    Suggested audiences (Discovered target segments, demographics,
    interests, platform fit, and relevance scores).

Main Question:
    "Who is likely to be interested in this content?"

Key Principle:
    The creator doesn't have to manually pick tags or demographics.
    The system automatically discovers them from content characteristics.
=========================================================
"""

import re
from typing import Dict, List, Any


class Agent2AudienceDiscovery:
    """
    AGENT 2 — AUDIENCE DISCOVERY AGENT
    """

    def __init__(self):
        print()
        print("=" * 60)
        print("👥 AGENT 2 — AUDIENCE DISCOVERY AGENT")
        print("=" * 60)
        print("Agent 2 initialized successfully.")

    def discover(self, content_profile: Dict[str, Any]) -> Dict[str, Any]:
        """
        Discover potential audience segments based on the content profile.
        """
        print()
        print("=" * 60)
        print("👥 AGENT 2 STARTED")
        print("=" * 60)

        # -------------------------------------------------
        # STEP 1 — EXTRACT KEY SIGNALS
        # -------------------------------------------------
        print()
        print("[Agent 2 - Step 1]")
        print("Extracting signals from Content Profile...")

        metadata = content_profile.get("video_metadata", {})
        text_analysis = content_profile.get("text_analysis", {})
        visual_analysis = content_profile.get("visual_analysis", {})

        # Extract OCR text tokens
        detected_texts = [
            item.get("text", "") 
            for item in text_analysis.get("detected_text", []) 
            if isinstance(item, dict)
        ]
        combined_text = " ".join(detected_texts).lower()

        orientation = metadata.get("orientation", "unknown")
        duration = metadata.get("duration_seconds", 0)

        print(f"✓ Signals processed: {len(detected_texts)} text cues, format: {orientation}, duration: {duration}s")

        # -------------------------------------------------
        # STEP 2 — TOPIC & NICHE CLUSTERING
        # -------------------------------------------------
        print()
        print("[Agent 2 - Step 2]")
        print("Inferring content topic and niche...")

        topics = self._infer_topics(combined_text, visual_analysis)
        primary_niche = topics[0] if topics else "General Lifestyle & Entertainment"

        print(f"✓ Primary niche identified: {primary_niche}")
        print(f"✓ Associated topics: {', '.join(topics)}")

        # -------------------------------------------------
        # STEP 3 — AUDIENCE SEGMENT GENERATION
        # -------------------------------------------------
        print()
        print("[Agent 2 - Step 3]")
        print("Generating target audience segments...")

        segments = self._generate_segments(topics, orientation, duration, combined_text)

        print(f"✓ Discovered {len(segments)} distinct audience segments.")

        # -------------------------------------------------
        # STEP 4 — PLATFORM & REACH SYNTHESIS
        # -------------------------------------------------
        print()
        print("[Agent 2 - Step 4]")
        print("Synthesizing platform fit and reach potential...")

        platform_fit = self._determine_platform_fit(orientation, duration)

        audience_profile = {
            "agent": {
                "id": "agent_2",
                "name": "Audience Discovery Agent"
            },
            "content_summary": {
                "primary_niche": primary_niche,
                "detected_topics": topics,
                "video_format": {
                    "orientation": orientation,
                    "duration_seconds": duration,
                    "format_type": "Short-Form" if duration <= 60 else "Long-Form"
                }
            },
            "platform_distribution": platform_fit,
            "audience_segments": segments,
            "overall_demographics": {
                "primary_age_bracket": segments[0]["age_range"] if segments else "18–24",
                "secondary_age_bracket": segments[1]["age_range"] if len(segments) > 1 else "25–34",
                "virality_vector": self._assess_virality_vector(segments, primary_niche)
            }
        }

        print("✓ Audience Profile generated.")

        # -------------------------------------------------
        # AGENT 2 COMPLETE
        # -------------------------------------------------
        print()
        print("=" * 60)
        print("👥 AGENT 2 COMPLETED")
        print("=" * 60)

        return audience_profile

    def _infer_topics(self, combined_text: str, visual_analysis: Dict[str, Any]) -> List[str]:
        """
        Identify topic clusters based on keywords and visual tags.
        """
        topic_keywords = {
            "Technology & Computer Science": [
                "computer", "coding", "code", "programming", "software", "tech", "lab", 
                "python", "data", "screen", "developer", "engineering", "ai", "hardware"
            ],
            "Education & Student Life": [
                "college", "university", "student", "study", "exam", "class", "lecture", 
                "campus", "school", "assignment", "course"
            ],
            "Travel & Exploration": [
                "travel", "budget", "trip", "tour", "explore", "vacation", "flight", 
                "hotel", "backpack", "destination", "road"
            ],
            "Business & Career": [
                "startup", "job", "career", "money", "finance", "business", "office", 
                "work", "productivity", "interview"
            ],
            "Fitness & Health": [
                "workout", "gym", "fitness", "diet", "healthy", "exercise", "muscle"
            ],
            "Entertainment & Pop Culture": [
                "viral", "challenge", "funny", "meme", "comedy", "movie", "music", "song"
            ]
        }

        scored_topics = []
        for topic, keywords in topic_keywords.items():
            matches = sum(1 for kw in keywords if re.search(r'\b' + re.escape(kw) + r'\b', combined_text))
            if matches > 0:
                scored_topics.append((topic, matches))

        scored_topics.sort(key=lambda x: x[1], reverse=True)

        if scored_topics:
            return [t[0] for t in scored_topics[:3]]
        
        # Default topic if text is sparse (e.g. lifestyle or visual)
        return ["Student & Campus Lifestyle", "Technology & Workplace Culture"]

    def _generate_segments(self, topics: List[str], orientation: str, duration: float, text: str) -> List[Dict[str, Any]]:
        """
        Generate distinct audience personas tailored to the inferred topics.
        """
        primary_topic = topics[0] if topics else ""

        if "Technology" in primary_topic or "Computer" in primary_topic or "Education" in primary_topic:
            return [
                {
                    "segment_id": 1,
                    "name": "College & Engineering Students",
                    "age_range": "18–24",
                    "persona": "Computer science, engineering, and IT undergraduates",
                    "interests": [
                        "Computer Lab Culture",
                        "Campus Life",
                        "Student Relatability",
                        "Tech Memes"
                    ],
                    "motivations": "Finding relatable humor, campus experiences, and peer bonding",
                    "consumption_habits": "Consumes short-form vertical reels during breaks between classes or study sessions",
                    "relevance_score": 0.94
                },
                {
                    "segment_id": 2,
                    "name": "Early-Career Tech Professionals",
                    "age_range": "21–28",
                    "persona": "Junior software engineers, IT associates, and tech interns",
                    "interests": [
                        "Office Environment",
                        "Tech Industry Culture",
                        "Workplace Humor",
                        "Career Upskilling"
                    ],
                    "motivations": "Relating to real-world tech workplaces, nostalgic for college lab days",
                    "consumption_habits": "Scrolls through social feeds during daily commutes and evening wind-down",
                    "relevance_score": 0.86
                },
                {
                    "segment_id": 3,
                    "name": "Casual Tech & Gadget Enthusiasts",
                    "age_range": "16–30",
                    "persona": "General social media audience interested in digital culture and PCs",
                    "interests": [
                        "Tech Trends",
                        "PC Setups",
                        "Digital Lifestyle",
                        "Short-form Entertainment"
                    ],
                    "motivations": "Casual curiosity about technology and behind-the-scenes office/lab culture",
                    "consumption_habits": "High engagement on algorithmic discovery pages (Instagram Explore / TikTok FYP)",
                    "relevance_score": 0.77
                }
            ]
        elif "Travel" in primary_topic:
            return [
                {
                    "segment_id": 1,
                    "name": "Budget & Solo Travelers",
                    "age_range": "18–26",
                    "persona": "Students and young travelers looking for affordable itineraries",
                    "interests": ["Budget Travel", "Hostels", "Backpacking", "Travel Hacks"],
                    "motivations": "Seeking cost-effective adventures and destination guides",
                    "consumption_habits": "Saves videos to collections and shares with friends",
                    "relevance_score": 0.95
                },
                {
                    "segment_id": 2,
                    "name": "Weekend & Domestic Explorers",
                    "age_range": "22–35",
                    "persona": "Working professionals planning quick getaways",
                    "interests": ["Domestic Tourism", "Weekend Trips", "Local Culture"],
                    "motivations": "Discovering reachable destinations without taking extended leave",
                    "consumption_habits": "Searches for specific travel itineraries on Instagram / YouTube",
                    "relevance_score": 0.88
                },
                {
                    "segment_id": 3,
                    "name": "Adventure Content Consumers",
                    "age_range": "18–34",
                    "persona": "Armchair travelers and outdoor enthusiasts",
                    "interests": ["Adventure Travel", "Cinematic Reels", "Scenic Spots"],
                    "motivations": "Visual escapism and inspiration for future trips",
                    "consumption_habits": "High like and share behavior on visually aesthetic video clips",
                    "relevance_score": 0.81
                }
            ]
        else:
            # Universal discovery segments
            return [
                {
                    "segment_id": 1,
                    "name": "Core Lifestyle & Trend Followers",
                    "age_range": "18–24",
                    "persona": "Active daily short-form video consumers",
                    "interests": ["Trending Audio", "Relatable Skits", "Social Trends"],
                    "motivations": "Quick entertainment, staying updated on viral trends",
                    "consumption_habits": "High propensity to share directly into direct message group chats",
                    "relevance_score": 0.90
                },
                {
                    "segment_id": 2,
                    "name": "Young Working Adults",
                    "age_range": "25–34",
                    "persona": "Professionals browsing content during breaks",
                    "interests": ["Everyday Humor", "Lifestyle Content", "Real-Life Observations"],
                    "motivations": "Stress relief and casual observation of everyday scenarios",
                    "consumption_habits": "Watches without sound or with captions enabled",
                    "relevance_score": 0.82
                },
                {
                    "segment_id": 3,
                    "name": "Broad Exploratory Viewers",
                    "age_range": "16–35",
                    "persona": "General social media algorithmic audience",
                    "interests": ["Viral Content", "Relatable Moments"],
                    "motivations": "Passive scrolling driven by platform recommendation engines",
                    "consumption_habits": "High drop-off if the hook doesn't land in the first 3 seconds",
                    "relevance_score": 0.74
                }
            ]

    def _determine_platform_fit(self, orientation: str, duration: float) -> List[Dict[str, Any]]:
        """
        Evaluate which social platforms are best suited for this format.
        """
        if orientation == "vertical":
            return [
                {"platform": "Instagram Reels", "suitability": "Optimal (95%)", "strength": "High student & young adult peer sharing"},
                {"platform": "YouTube Shorts", "suitability": "Optimal (92%)", "strength": "Strong algorithmic evergreen discovery"},
                {"platform": "TikTok", "suitability": "Optimal (90%)", "strength": "Rapid hook-driven virality potential"}
            ]
        else:
            return [
                {"platform": "YouTube", "suitability": "Optimal (95%)", "strength": "Best for landscape long-form search & watch time"},
                {"platform": "LinkedIn Video", "suitability": "High (82%)", "strength": "Effective for workplace & educational clips"},
                {"platform": "Facebook Video", "suitability": "Moderate (70%)", "strength": "Broader older demographic reach"}
            ]

    def _assess_virality_vector(self, segments: List[Dict[str, Any]], primary_niche: str) -> str:
        """
        Provide strategic insight into why this content can spread virally.
        """
        top_segment = segments[0]["name"] if segments else "General Audience"
        return (
            f"High peer-to-peer shareability within '{top_segment}'. "
            f"Content resonates strongly with '{primary_niche}' culture, "
            f"driving direct message (DM) forwarding and comment tagging."
        )
